services:
  - type: web
    name: access-mobile-web
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /sw.js
        name: Cache-Control
        value: no-cache
      - path: /manifest.json
        name: Cache-Control
        value: no-cache
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
